
import { DesignPreset } from '../types';

export const DESIGN_PRESETS: DesignPreset[] = [
  // --- Modern/Tech ---
  { id: 'cyberpunk', label: 'Cyberpunk 2077', description: 'High contrast, neon blues and pinks, glitch effects, dystopian utility.', category: 'Modern/Tech', tags: ['Neon', 'Dark', 'Glitch'] },
  { id: 'neumorphism', label: 'Neumorphism', description: 'Soft shadows, extruded shapes, minimal color, tactile plastic feel.', category: 'Modern/Tech', tags: ['Soft', '3D', 'Light'] },
  { id: 'glassmorphism', label: 'Glassmorphism', description: 'Translucent frosted glass layers, vivid background blurs, white borders.', category: 'Modern/Tech', tags: ['Blur', 'Transparency', 'Modern'] },
  { id: 'claymorphism', label: 'Claymorphism', description: 'Fluffy 3D shapes, floating elements, matte types, friendly aesthetic.', category: 'Modern/Tech', tags: ['3D', 'Round', 'Playful'] },
  { id: 'material3', label: 'Material You (M3)', description: 'Dynamic color extraction, playful shapes, large touch targets.', category: 'Modern/Tech', tags: ['Google', 'Adaptive', 'Colorful'] },
  { id: 'ios17', label: 'Cupertino (iOS 17)', description: 'Translucency, thin strokes, SF Symbols, refined typography.', category: 'Modern/Tech', tags: ['Apple', 'Clean', 'Blur'] },
  { id: 'bento', label: 'Bento Grid', description: 'Modular content blocks, distinct rounded corners, hierarchy by size.', category: 'Modern/Tech', tags: ['Grid', 'Organized', 'Apple'] },
  { id: 'linear', label: 'Linear', description: 'Subtle gradients, glowing borders, dark mode default, particle effects.', category: 'Modern/Tech', tags: ['SaaS', 'Dark', 'Glow'] },
  { id: 'solar-punk', label: 'Solar Punk', description: 'Organic technology, greens and golds, stained glass, Art Nouveau tech.', category: 'Modern/Tech', tags: ['Eco', 'Bright', 'Organic'] },
  { id: 'holographic', label: 'Holographic', description: 'Iridescent foils, chromatic aberration, shifting gradients.', category: 'Modern/Tech', tags: ['Shiny', 'Rainbow', 'Futuristic'] },
  { id: 'spatial', label: 'Spatial UI', description: 'Floating panels, depth cues, eye-tracking ready, volumetric.', category: 'Modern/Tech', tags: ['VR', 'AR', 'Depth'] },
  { id: 'aero', label: 'Windows Aero', description: 'Glossy reflections, glass borders, skepticism of flat design.', category: 'Modern/Tech', tags: ['Gloss', 'Nostalgia', 'Transparent'] },
  { id: 'fluent', label: 'Fluent Design', description: 'Acrylic material, connected animations, light and depth.', category: 'Modern/Tech', tags: ['Microsoft', 'Light', 'Depth'] },
  { id: 'skeuomorphic-redux', label: 'Skeuomorphic Redux', description: 'Hyper-realistic textures (leather, wood) specifically for high-res displays.', category: 'Modern/Tech', tags: ['Texture', 'Realism', 'Tactile'] },
  { id: 'hud', label: 'Sci-Fi HUD', description: 'Thin lines, target reticles, monospace data streams, purely functional.', category: 'Modern/Tech', tags: ['Space', 'Data', 'Interface'] },
  { id: 'anime-dreams', label: 'Anime Dreams', description: 'Bright pastel palette, dramatic shadows, and dreamy design layouts.', category: 'Modern/Tech', tags: ['Anime', 'Pastel', 'Dreamy'] },
  { id: 'industrial-futurism', label: 'Industrial Futurism', description: 'Modern, high-tech minimalism with precise grid systems.', category: 'Modern/Tech', tags: ['Industrial', 'Minimal', 'Precision'] },
  { id: 'silicon-valley-minimal', label: 'Silicon Valley Minimal', description: 'Tech industry-inspired designs with approachable color balance.', category: 'Modern/Tech', tags: ['Tech', 'Clean', 'Minimal'] },

  // --- Retro ---
  { id: '8bit', label: '8-Bit Pixel', description: 'Blocky fonts, restricted color palette, scanlines, NES nostalgia.', category: 'Retro', tags: ['Pixel', 'Game', 'Fun'] },
  { id: 'vaporwave', label: 'Vaporwave', description: 'Purple/Teal gradients, marble statues, Japanese text, windows 95 nostalgia.', category: 'Retro', tags: ['Aesthetic', 'Surreal', 'Gradient'] },
  { id: 'bauhaus', label: 'Bauhaus', description: 'Primary colors, strict geometry, form follows function, sans-serif.', category: 'Retro', tags: ['Art', 'Geometric', 'Bold'] },
  { id: 'brutalism', label: 'Neo-Brutalism', description: 'Default web safe fonts, black borders, high contrast, raw unstyled look.', category: 'Retro', tags: ['Raw', 'Bold', 'Ugly-Beautiful'] },
  { id: 'newsprint', label: 'New York Newsprint', description: 'Serif headlines, multi-column layout, monochrome, paper texture.', category: 'Retro', tags: ['Classic', 'Text', 'Editorial'] },
  { id: 'y2k', label: 'Y2K Aesthetic', description: 'Chrome blobs, bubbly fonts, matrix green, icy blues, futuristic optimism.', category: 'Retro', tags: ['2000s', 'Chrome', 'Shiny'] },
  { id: 'win95', label: 'Windows 95', description: 'Beveled gray buttons, pixelated icons, navy blue title bars.', category: 'Retro', tags: ['OS', 'Gray', 'Classic'] },
  { id: 'terminal', label: 'DOS Terminal', description: 'Green or amber phosphor text on black, blinking cursor, command line.', category: 'Retro', tags: ['Code', 'Hacker', 'Monospace'] },
  { id: 'popart', label: 'Pop Art', description: 'Halftone dots, comic book outlines, explosive colors.', category: 'Retro', tags: ['Comic', 'Bold', 'Pattern'] },
  { id: 'art-deco', label: 'Art Deco', description: 'Gold leaf, symmetry, geometric ornamentation, luxury.', category: 'Retro', tags: ['Luxury', 'Gold', 'Classic'] },
  { id: 'victorian', label: 'Victorian', description: 'Ornate flourishes, woodcut styles, parchment backgrounds.', category: 'Retro', tags: ['Old', 'Fancy', 'Detailed'] },
  { id: 'synthwave', label: 'Synthwave', description: 'Sunset grids, chrome typography, outrun aesthetics.', category: 'Retro', tags: ['80s', 'Neon', 'Night'] },
  { id: 'mid-century', label: 'Mid-Century Modern', description: 'Muted pastels, organic curves, atomic age motifs.', category: 'Retro', tags: ['50s', 'Clean', 'Warm'] },
  { id: 'teletext', label: 'Teletext', description: 'Strict grid, 8 colors, block graphics, TV information service.', category: 'Retro', tags: ['TV', 'Blocky', 'Info'] },
  { id: 'blueprint', label: 'Blueprint', description: 'Cyan background, white lines, technical diagrams, handwritten notes.', category: 'Retro', tags: ['Technical', 'Sketch', 'Blue'] },
  { id: 'steampunk-vintage', label: 'Steampunk Vintage', description: 'Antique gears, bold metallic tones, and intricate designs from the industrial era.', category: 'Retro', tags: ['Steampunk', 'Vintage', 'Industrial'] },
  { id: 'vaporwave-90s', label: '90s Vaporwave', description: 'Gradient sunsets, palm trees, and retro artifacts driven by nostalgia.', category: 'Retro', tags: ['Vaporwave', 'Nostalgia', '1990s'] },
  { id: 'cheerful-kids', label: 'Cheerful Kids', description: 'Bright, cheerful, and vibrant colors with playful, kid-focused layouts.', category: 'Retro', tags: ['Cheerful', 'Bright', 'Kids'] },
  { id: 'classic-elegance', label: 'Classic Elegance', description: 'Timeless serif fonts, monochrome palettes, and a sense of historic opulence.', category: 'Retro', tags: ['Classic', 'Elegant', 'Timeless'] },
  { id: 'arabesque-vibrance', label: 'Arabesque Vibrance', description: 'Exotic intricate patterns blended into quirky motifs and modern storytelling.', category: 'Retro', tags: ['Ornate', 'Exotic', 'Bold'] },

  // --- Minimal ---
  { id: 'monochrome', label: 'Strict Monochrome', description: 'Pure black and white. No grays. Reliance on spacing and size.', category: 'Minimal', tags: ['Stark', 'Clean', 'Bold'] },
  { id: 'swiss', label: 'Swiss Style', description: 'Asymmetric layouts, strong grid usage, Helvetica, negative space.', category: 'Minimal', tags: ['Typography', 'Grid', 'Clean'] },
  { id: 'scandi', label: 'Scandinavian', description: 'Warm whites, light woods, functional, cozy (Hygge).', category: 'Minimal', tags: ['Warm', 'Clean', 'Natural'] },
  { id: 'zen', label: 'Wabi-Sabi', description: 'Earth tones, rough textures, impermanence, asymmetry.', category: 'Minimal', tags: ['Organic', 'Peaceful', 'Texture'] },
  { id: 'ink', label: 'E-Ink', description: 'High contrast, slow refresh aesthetic, paper-like readability.', category: 'Minimal', tags: ['Readability', 'Paper', 'Tech'] },
  { id: 'wireframe', label: 'Lo-Fi Wireframe', description: 'Hand-drawn lines, placeholders, focus on structure over style.', category: 'Minimal', tags: ['Sketch', 'Draft', 'Simple'] },
  { id: 'darkroom', label: 'Darkroom', description: 'Deep reds and blacks, preserving night vision, minimal glare.', category: 'Minimal', tags: ['Dark', 'Red', 'Utility'] },
  { id: 'lab', label: 'Laboratory', description: 'Sterile white, clinical blue accents, data-focused, precise.', category: 'Minimal', tags: ['Clean', 'Medical', 'Science'] },
  { id: 'typography', label: 'Kinetic Typography', description: 'Type as image. Massive fonts, moving text, minimal imagery.', category: 'Minimal', tags: ['Type', 'Motion', 'Bold'] },
  { id: 'luxury-min', label: 'High Luxury', description: 'Lots of white space, serif fonts, gold thin lines, sparse content.', category: 'Minimal', tags: ['Expensive', 'Elegant', 'Sparse'] },
  { id: 'institutional', label: 'Institutional', description: 'Government forms, brutal functionality, unstyled Times New Roman.', category: 'Minimal', tags: ['Boring', 'Official', 'Dry'] },
  { id: 'architectural', label: 'Architectural', description: 'Fine lines, precise measurements, structural layouts.', category: 'Minimal', tags: ['Structure', 'Lines', 'Plan'] },
  { id: 'desert', label: 'Desert Modern', description: 'Terracotta, sage, sand, expansive spacing, heat.', category: 'Minimal', tags: ['Warm', 'Nature', 'Dry'] },
  { id: 'polar', label: 'Polar', description: 'Icy blues, whites, sharp edges, cold precision.', category: 'Minimal', tags: ['Cold', 'Clean', 'Sharp'] },
  { id: 'print', label: 'High-End Print', description: 'Looks like a magazine. Drop caps, justified text, gutters.', category: 'Minimal', tags: ['Editorial', 'Classy', 'Paper'] },
  { id: 'pastel-plains', label: 'Pastel Plains', description: 'Soft palettes with an entirely calm and gentle visual experience.', category: 'Minimal', tags: ['Pastel', 'Calm', 'Minimal'] },
  { id: 'arctic-mist', label: 'Arctic Mist', description: 'Cool blues and whites combined with transparency effects for a frosty feel.', category: 'Minimal', tags: ['Frosty', 'Transparent', 'Cool'] },
  { id: 'golden-luxury', label: 'Golden Luxury', description: 'Refined aesthetics with rich gold hues, bold typography, and minimal layouts.', category: 'Minimal', tags: ['Gold', 'Elegant', 'Luxury'] },
  { id: 'rustic-earth', label: 'Rustic Earth', description: 'Natural earthy tones, rustic finishes, and textured backgrounds.', category: 'Minimal', tags: ['Rustic', 'Earthy', 'Natural'] },
  { id: 'forest-zen', label: 'Forest Zen', description: 'Lush greens, earthy tones, and tranquil Zen-inspired designs.', category: 'Minimal', tags: ['Forest', 'Zen', 'Natural'] },
  { id: 'meditative-light', label: 'Meditative Light', description: 'Soft and serene designs targeting peaceful mindfulness with subtle typography.', category: 'Minimal', tags: ['Meditative', 'Soft', 'Peaceful'] },

  // --- Experimental ---
  { id: 'glitch', label: 'Glitch Art', description: 'Corrupted data, RGB splitting, noise, intentional errors.', category: 'Experimental', tags: ['Chaos', 'Digital', 'Noise'] },
  { id: 'antidesign', label: 'Anti-Design', description: 'Ignoring grids, overlapping text, clashing colors, raw expression.', category: 'Experimental', tags: ['Rebel', 'Messy', 'Art'] },
  { id: 'maximalism', label: 'Maximalism', description: 'Fill every space. Patterns on patterns. Sensory overload.', category: 'Experimental', tags: ['Busy', 'Loud', 'Fun'] },
  { id: 'grunge', label: '90s Grunge', description: 'Dirty textures, torn paper, handwriting, distressed type.', category: 'Experimental', tags: ['Dirty', 'Rock', 'Texture'] },
  { id: 'organic', label: 'Bio-Digital', description: 'Cells, slime molds, generative growth patterns, nature meets code.', category: 'Experimental', tags: ['Nature', 'Weird', 'Growth'] },
  { id: 'psychedelic', label: 'Psychedelic', description: 'Liquid distortions, warping grids, impossible colors.', category: 'Experimental', tags: ['Trippy', 'Fluid', 'Color'] },
  { id: 'collage', label: 'Mixed Media Collage', description: 'Cutouts from different eras, paper textures, torn edges.', category: 'Experimental', tags: ['Art', 'Paper', 'Retro'] },
  { id: 'deconstruct', label: 'Deconstructivism', description: 'Fragmented shapes, non-rectilinear shapes, dynamic tension.', category: 'Experimental', tags: ['Broken', 'Angle', 'Sharp'] },
  { id: 'ascii', label: 'ASCII Art', description: 'Everything is text characters. Images rendered as strings.', category: 'Experimental', tags: ['Code', 'Text', 'Retro'] },
  { id: 'dream', label: 'Dreamcore', description: 'Liminal spaces, unsettling nostalgia, soft focus, odd lighting.', category: 'Experimental', tags: ['Surreal', 'Soft', 'Creepy'] },
  { id: 'frutiger', label: 'Frutiger Aero', description: 'Glossy globes, water splashes, grassy fields, utopian tech.', category: 'Experimental', tags: ['2000s', 'Fresh', 'Gloss'] },
  { id: 'corporate', label: 'Corporate Memphis', description: 'Flat vector people, purple skin, oversized limbs, joyful flat color.', category: 'Experimental', tags: ['Flat', 'Illustration', 'Tech'] },
  { id: 'abstract', label: 'Abstract Geom', description: 'Kandinsky-esque shapes, lines, and colors interacting.', category: 'Experimental', tags: ['Art', 'Shape', 'Color'] },
  { id: 'noise', label: 'Static Noise', description: 'Heavy grain overlays, signal loss, hidden information.', category: 'Experimental', tags: ['Texture', 'Rough', 'Dark'] },
  { id: 'rave', label: 'Acid Rave', description: 'Smileys, yellow and black, distortion, repetitive patterns.', category: 'Experimental', tags: ['Party', 'Loud', 'Bold'] },
  { id: 'neon-future', label: 'Neon Future', description: 'Bright glowing neon colors, dark backgrounds, futuristic appearances.', category: 'Experimental', tags: ['Neon', 'Cyber', 'Futuristic'] },
  { id: 'cyberpunk-city', label: 'Cyberpunk City', description: 'Dystopian vibes with glowing signs, gritty textures, and retro-modern style.', category: 'Experimental', tags: ['Cyberpunk', 'Cityscape', 'Retro'] },
  { id: 'geometricsplash', label: 'Geometric Splash', description: 'Bold and vibrant geometric patterns blended with soft gradients.', category: 'Experimental', tags: ['Shapes', 'Patterns', 'Abstract'] },
  { id: 'bold-street-art', label: 'Bold Street Art', description: 'Street art-inspired graffiti designs, vivid expressive storytelling by streetstyle.', category: 'Experimental', tags: ['Street Art', 'Graffiti'] },
  { id: 'kaleidoscope', label: 'Kaleidoscope', description: 'Intricate color reflections and symmetrical layouts like glass.', category: 'Experimental', tags: ['Reflective', 'Symmetry', 'Abstract'] },
  { id: 'digital-matrix', label: 'Digital Matrix', description: 'Abstract digital rain effects, inspired by matrix-style visuals.', category: 'Experimental', tags: ['Matrix', 'Digital', 'Abstract'] },
  { id: 'galactic-space', label: 'Galactic Space', description: 'Cosmic themes, vivid nebulae, galaxy patterns, and starry palettes.', category: 'Experimental', tags: ['Galaxy', 'Space', 'Cosmic'] },
  { id: 'psychedelic-dreams', label: 'Psychedelic Dreams', description: 'Swirling colors, bright contrasts, and a trippy fluidity to design.', category: 'Experimental', tags: ['Psychedelic', 'Trippy', 'Colorful'] },
  { id: 'retro-future-optimism', label: 'Retro Future Optimism', description: 'Futuristic layouts with a vintage tech-flavored charm.', category: 'Experimental', tags: ['Retro', 'Futuristic', 'Tech'] },
  { id: 'electric-vibe', label: 'Electric Vibrance', description: 'Energetic electric color schemes with high-tech gradient flashes.', category: 'Experimental', tags: ['Electric', 'Gradient', 'Vibrant'] },
  { id: 'punk-chaos', label: 'Punk Chaos', description: 'Clashing colors, busy patterns, and rebellious anti-design elements.', category: 'Experimental', tags: ['Punk', 'Rebellious', 'Chaotic'] },
  { id: 'liquid-metal', label: 'Liquid Metal', description: 'Molten chrome, fluid distortions, metallic gradients.', category: 'Experimental', tags: ['Chrome', '3D', 'Fluid'] },
  { id: 'cyber-sigil', label: 'Cyber Sigilism', description: 'Tribal Y2K sharp lines, gothic tech fonts, high contrast.', category: 'Experimental', tags: ['Gothic', 'Sharp', 'Y2K'] },
  { id: 'risograph', label: 'Risograph', description: 'Print misalignment, multiply blends, grain, vibrant ink.', category: 'Experimental', tags: ['Print', 'Grain', 'Colorful'] },
  { id: 'acid-graphix', label: 'Acid Graphix', description: 'Distorted type, chrome, anti-gravity layouts, rave culture.', category: 'Experimental', tags: ['Acid', 'Distorted', 'Trippy'] },
  { id: 'neo-noir', label: 'Neo-Noir', description: 'High contrast B&W, rain, shadows, venetian blinds, detective vibes.', category: 'Experimental', tags: ['Dark', 'Cinema', 'Mystery'] },
  { id: 'ethereal', label: 'Ethereal Angel', description: 'Soft lens flares, heavenly glows, delicate gradients, dreamlike.', category: 'Experimental', tags: ['Soft', 'Glow', 'Light'] },

  // --- Animated ---
  { id: 'kinetic-motion', label: 'Kinetic Motion', description: 'Constant movement, scrolling text, jittery elements, high energy.', category: 'Animated', tags: ['Motion', 'Type', 'Fast'] },
  { id: 'fluid-simulation', label: 'Fluid Simulation', description: 'Morphing blobs, slow drifts, color cycling, organic flow.', category: 'Animated', tags: ['Fluid', 'Soft', 'Morph'] },
  { id: 'particle-data', label: 'Particle Data', description: 'Floating nodes, twinkling grid points, data streams, technical.', category: 'Animated', tags: ['Data', 'Tech', 'Particles'] },
];